### ISSUE TITLE
Bridge fails to generate the correct method signature

### ISSUE THREAD

**Issue by piercifani** [skiptools/skip-bridge#81]
Given this Swift protocol:

```swift
public protocol FooAPIClientNetworkFetcher {
    func fetchData(with url: URL, method: String, httpHeaders: [String: String], body: Data?) async throws -> FooAPIClientResponse
}
```

After `skip export`, it gets translated to:

```kotlin
public interface FooAPIClientNetworkFetcher {
    public abstract suspend fun fetchData(with: skip.foundation.URL, method: kotlin.String, httpHeaders: skip.lib.Dictionary<kotlin.String, kotlin.String>, body: skip.foundation.Data?): foo.module.FooAPIClientResponse
}
```

However, it looks like the generated code doesn't match what the JVM is expecting, making the app crash at runtime `foo/FooAPIClient_Bridge.swift:32: Fatal error: Unexpectedly found nil while unwrapping an Optional value` where the relevant section of this Swift file is:

![Image](https://github.com/user-attachments/assets/b7b6be69-45ca-449a-b53c-23022b787c41)

Attaching a ZIP with the project: [crash-android-bridge.zip](https://github.com/user-attachments/files/19855811/crash-android-bridge.zip)

**Comment by aabewhite** [comment]
I haven't tried it on your sample project, but this *should* be fixed in the just-released Skip transpiler version 1.4.13

**Comment by piercifani** [comment]
Nope... I see now that the method signature changed from:

```kotlin
public abstract suspend fun fetchData(with: skip.foundation.URL, method: kotlin.String, httpHeaders: skip.lib.Dictionary<kotlin.String, kotlin.String>, body: skip.foundation.Data?): foo.module.FooAPIClientResponse
```
to:

```kotlin
public override suspend fun fetchData(with: java.net.URI, method: kotlin.String, httpHeaders: kotlin.collections.Map<kotlin.String, kotlin.String>, body: kotlin.ByteArray?): foo.module.FooAPIClientResponse {
```

But I still get a `foo/FooAPIClient_Bridge.swift:32: Fatal error: Unexpectedly found nil while unwrapping an Optional value`

The generated file looks like this:

<img width="1191" alt="Image" src="https://github.com/user-attachments/assets/0f50245f-d7c0-44d0-8aa0-54699ade3e04" />

**Comment by aabewhite** [comment]
Ah, I missed the async aspect. That will take some additional work

**Comment by piercifani** [comment]
Hello @aabewhite! Any ETA on this? Just to understand if we need to figure out a workaround or not :)

**Comment by aabewhite** [comment]
OK, I got your sample working with skip-1.5.10. Note that because you're using .kotlincompat, your KotlinNetworkFetcher needs a different fetchData signature. Here is what I used:

```
class KotlinNetworkFetcher: FooAPIClientNetworkFetcher {
    public override suspend fun fetchData(with: java.net.URI, method: kotlin.String, httpHeaders: kotlin.collections.Map<kotlin.String, kotlin.String>, body: kotlin.ByteArray?): foo.module.FooAPIClientResponse {
        // Build RequestBody if needed
        val requestBody: RequestBody? = when (method.uppercase()) {
            "POST", "PUT", "PATCH" ->
                body?.toRequestBody(null)
            else -> null
        }

        // Build headers
        val headersBuilder = Headers.Builder()
        for (key in httpHeaders.keys) {
            val value = httpHeaders.get(key)
            if (value != null) {
                headersBuilder.add(key, value)
            }
        }
        // Build Request
        val request = Request.Builder()
            .url(with.toString())
            .method(method.uppercase(), requestBody)
            .headers(headersBuilder.build())
            .build()

        // Build client (timeouts are optional)
        val client = OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .writeTimeout(15, TimeUnit.SECONDS)
            .build()

        // Execute request
        val response = client.newCall(request).execute()

        val responseBody = response.body?.bytes() ?: ByteArray(0)
        val statusCode = response.code
        val responseUrl = response.request.url.toUri()

        return foo.module.FooAPIClientResponse(responseBody, statusCode, responseUrl)
    }
}
```

**Comment by piercifani** [comment]
It now works correctly! Thanks a lot!
